name: CI - Test and Lint

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint
      continue-on-error: true

    - name: Run type checking (if TypeScript)
      run: npm run type-check 2>/dev/null || echo "No TypeScript type checking available"
      continue-on-error: true

    - name: Run tests
      run: npm test 2>/dev/null || echo "No tests configured"
      continue-on-error: true

    - name: Build application
      run: npm run build

    - name: Check build output
      run: |
        if [ -d "dist" ]; then
          echo "Build successful - dist directory created"
          ls -la dist/
        else
          echo "Build failed - no dist directory found"
          exit 1
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: matrix.node-version == '18.x'
      with:
        name: build-artifacts
        path: dist/
        retention-days: 7

  lighthouse:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Serve application
      run: |
        npm install -g serve
        serve -s dist -l 3000 &
        sleep 5
      
    - name: Run Lighthouse CI
      uses: treosh/lighthouse-ci-action@v11
      with:
        urls: |
          http://localhost:3000
        configPath: './.lighthouserc.json'
        uploadArtifacts: true
        temporaryPublicStorage: true 